name: Deploy WAR to Tomcat on EC2

on:
#  pull_request:
#    branches: [ "main" ]
  push:
    branches: ["deploy"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Fake Tomcat dir
        run: mkdir -p fake-tomcat
      
      - name: Install Ant
        run: sudo apt-get install ant -y
        
      - name: List Ant Targets
        run: ant -p
        
      - name: Build with Ant
        run: ant -Dj2ee.server.home=$(pwd)/fake-tomcat dist
        
      - name: Debug WAR path
        run: |
          echo "Current dir: $(pwd)"
          find . -name "*.war"
          
      - name: Copy WAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/EduPlan.war"
          target: "/opt/tomcat10/webapps/"

      - name: Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop tomcat
            sudo rm -rf /opt/tomcat10/webapps/EduPlan /opt/tomcat10/webapps/EduPlan.war
            sudo cp ~/EduPlan.war /opt/tomcat10/webapps/
            sudo systemctl start tomcat
